### ISSUE TITLE
It is essentail that run shell with root privilige, but no remind in README.

### ISSUE THREAD

**Issue by BruceWind** [tmplink/prophet_client#1]
By the time I run `curl -k 'https://raw.githubusercontent.com/tmplink/prophet_client/main/install.sh' | sh`, I got errors. 
Then I think over why it happend, I found that I run it without root privilege.

Pls, write down `root privilege` on READ me for users.

In addition to, Although I got error, the terminal still got the message `Prophet installed`, I thought it is unexpected in this situation.

**Comment by tmplink** [comment]
Welcome to submitting PR

**Comment by BruceWind** [comment]
Hello, Bro. 
I sent a PR: https://github.com/tmplink/prophet_client/pull/2 for this repo.
